Tracker_Webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # /
    url(r'^$', views.index),

    # /tracker
    url(r'^tracker/', include('tracker.urls')),
]

tracker/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required

app_name = "tracker"

urlpatterns = [
    # default homepage (index site)

    # Test
    # /tracker
    url(r'^$', views.index, name='index'),

    # /tracker/home
    url(r'^home/$', views.index, name='home'),

    # /tracker/register
    url(r'^register/$', views.RegisterUserFormView.as_view(), name='register'),

    # /tracker/login
    url(r'^login/$', views.LoginUserFormView.as_view(), name='login'),

    # /tracker/logout
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    # /tracker/app
    url(r'^app/$', views.TrackListView.as_view(), name='tracker_app'),

    # /tracker/app/decs/<id>
    url(r'^app/decs/(?P<track_id>[0-9]+)$', views.decrementSeason, name='dec_season'),

    # /tracker/app/incs/<id>
    url(r'^app/incs/(?P<track_id>[0-9]+)$', views.incrementSeason, name='inc_season'),

    # /tracker/app/dece/<id>
    url(r'^app/dece/(?P<track_id>[0-9]+)$', views.decrementEpisode, name='dec_episode'),

    # /tracker/app/ince/<id>
    url(r'^app/ince/(?P<track_id>[0-9]+)$', views.incrementEpisode, name='inc_episode'),

    # /tracker/app/add/
    url(r'^app/add_track/$', views.CreateNewTrackFormView.as_view(), name='add_track'),

    # /tracker/app/edit/<id>
    url(r'^app/edit/(?P<pk>[0-9]+)$', views.EditExistingTrack.as_view(), name='edit_track'),

    # /tracker/app/delete/<id>
    url(r'^app/delete/(?P<pk>[0-9]+)$', views.DeleteExistingTrack.as_view(), name='delete_track'),
]

tracker/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.conf import settings

class Track(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, unique=False) # so one user can have multiple tracks
    title = models.CharField(max_length=500)
    season = models.IntegerField(default=1)
    episode = models.IntegerField(default=1)
    started = models.DateTimeField()

    def get_absolute_url(self):
        return reverse("tracker:index")

    def __str__(self):
        return "Owner: " + self.user.username + ", Title: " + self.title

tracker/forms.py
from django.contrib.auth.models import User
from django import forms
from django.db import models
from django.contrib.auth.forms import AuthenticationForm
from django.forms import TextInput, PasswordInput, DateTimeInput, NumberInput
from .models import Track

style = 'border-color: black; border-width: 3px; font-weight: bold; font-size: medium; padding-left: 7px;'
width = 'col-sm-5'


class UserForm(forms.ModelForm):
    # style = 'border-color: black; border-width: 3px; font-weight: bold; font-size: medium; padding-left: 7px;'
    # width = 'col-sm-5'

    email = forms.CharField(widget=TextInput(attrs={'style': style, 'class': width}))
    username = forms.CharField(widget=TextInput(attrs={'style': style, 'class': width}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'style': style, 'class': width}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'style': style, 'class': width}))
    first_name = forms.CharField(max_length=100, widget=TextInput(attrs={'style': style, 'class': width}))
    last_name = forms.CharField(max_length=100, widget=TextInput(attrs={'style': style, 'class': width}))

    class Meta:
        model = User
        fields = ["email", "username", "password", "confirm_password", "first_name", "last_name"]

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Password and confirmed password did not match")


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={'style': style, 'class': width}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'style': style, 'class': width}))


class TrackForm(forms.ModelForm):
    title = models.CharField()
    season = models.PositiveIntegerField()
    episode = models.PositiveIntegerField()
    started = models.DateTimeField()

    class Meta:
        model = Track
        fields = ["title", "season", "episode"]
        widgets = {
            'title': TextInput(attrs={'style': style, 'class': width}),
            'season': NumberInput(attrs={'style': style, 'class': width}),
            'episode': NumberInput(attrs={'style': style, 'class': width}),
        }

tracker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.views.generic import View, UpdateView, DeleteView, CreateView
from django.views import generic
from .forms import UserForm, UserLoginForm, TrackForm
from django.contrib.auth import authenticate, login, logout
from django.http import *
from .models import Track
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from datetime import datetime


class IndexView(View):
    template_name = "tracker/base.html"

    def get(self, request):
        return HttpResponse("<h1>Index</h1>")


'''
    Methods e.g. login
'''


def index(request):
    return render(request, "tracker/index.html")


@login_required(login_url="tracker:login")
def decrementSeason(request, track_id):
    my_track = Track.objects.get(id=track_id)
    season = my_track.season
    new_season = season - 1
    # no ability to start at season 0. season 1 is the first season
    if new_season < 1:
        # don't perform any updates
        messages.info(request, "You are already on the first season!")
        return redirect("tracker:tracker_app")

    my_track.season = new_season
    my_track.save()
    messages.info(request, "Updated: " + my_track.title)
    return redirect("tracker:tracker_app")


@login_required(login_url="tracker:login")
def incrementSeason(request, track_id):
    my_track = Track.objects.get(id=track_id)
    season = my_track.season
    new_season = season + 1
    if new_season > 100:
        messages.info(request, "Maximum limit of 100 seasons reached!")
        return redirect("tracker:tracker_app")
    my_track.season = new_season
    my_track.save()
    messages.info(request, "Updated: " + my_track.title)
    return redirect("tracker:tracker_app")


@login_required(login_url="tracker:login")
def decrementEpisode(request, track_id):
    my_track = Track.objects.get(id=track_id)
    episode = my_track.episode
    new_episode = episode - 1
    # no ability to start at episode 0. episode 1 is the first episode
    if new_episode < 1:
        # don't perform any updates
        messages.info(request, "You are already on the first episode!")
        return redirect("tracker:tracker_app")

    my_track.episode = new_episode
    my_track.save()
    messages.info(request, "Updated: " + my_track.title)
    return redirect("tracker:tracker_app")


@login_required(login_url="tracker:login")
def incrementEpisode(request, track_id):
    my_track = Track.objects.get(id=track_id)
    episode = my_track.episode
    new_episode = episode + 1
    if new_episode > 2500:
        messages.info(request, "Maximum limit of 2500 episodes reached!")
        return redirect("tracker:tracker_app")
    my_track.episode = new_episode
    my_track.save()
    messages.info(request, "Updated: " + my_track.title)
    return redirect("tracker:tracker_app")


@login_required(login_url="tracker:login")
def editTrack(request, track_id):
    return redirect("tracker:index")


'''
    Classes e.g. ModelViews
'''


class RegisterUserFormView(View):
    form_class = UserForm
    template_name = "tracker/register_form.html"

    username = ""

    # First access to page
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    # Submit of registration form
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)  # do not save to the DB yet

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user.set_password(password)
            user.save()

            #return redirect("tracker:index")
            return render(request, "tracker/registration_success.html", {"form": form, "username": username})
        return render(request, self.template_name, {"form": form})




class LoginUserFormView(View):
    form_class = UserLoginForm
    template_name = "tracker/login_form.html"

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)

        # debug
        if form.is_valid():
            print("form is valid")
        else:
            print("form.errors: " + str(form.errors))
            print("form.non_field_errors: " + str(form.non_field_errors))
            print("form is not valid")

        if form.is_valid():
            # return redirect("http://google.de")
            # user = form.save(commit=False)

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # use special password to set the hashed password (plaintext comparison is unsafe)
            # user.set_password(password)

            # authenticate user
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)

                # if user.is_active:
                #     login(request, user)

                return redirect("tracker:index")
            return render(request, self.template_name,
                          {"form": form, "login_error": "Username and password did not match."})
        else:
            # return redirect("http://bing.com")
            return render(request, self.template_name, {"form": form})


class TrackListView(LoginRequiredMixin, generic.ListView):
    login_url = "tracker:login"
    template_name = "tracker/tracker_view.html"
    context_object_name = "all_tracks"

    def get_queryset(self):
        username = self.request.user.username
        return Track.objects.filter(user__username=username).order_by('title')


class CreateNewTrackFormView(View):
    form_class = TrackForm
    template_name = "tracker/add_new_track.html"

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            track = form.save(commit=False)
            track.user = request.user
            track.started = datetime.now()
            track.save()
            return redirect("tracker:tracker_app")
        else:
            return render(request, self.template_name,
                          {"form": form, "add_error": "Sorry! We could not add your track. Please try again later."})


class EditExistingTrack(UpdateView):
    model = Track
    form_class = TrackForm
    template_name = "tracker/edit_track.html"
    # fields = ["title", "season", "episode"]
    success_url = reverse_lazy("tracker:tracker_app")

class DeleteExistingTrack(DeleteView):
    model = Track
    success_url = reverse_lazy("tracker:tracker_app")

tracker/templates/tracker/add_new_track.html
{% extends "tracker/base.html" %}

{% block title %} Add new Track {% endblock %}

{% block tracker_active %} active {% endblock %}

{% block body %}

    {% if add_error %}
        <p class="col-sm-offset-4">{{ add_error }}</p>
    {% endif %}

    <form class="form-horizontal col-sm-offset-3" action="" method="post" role="form">
        <!-- Security -->
        {% csrf_token %}
        {% include "tracker/form_template.html" %}
        <button type="submit" class="custombtn btn col-sm-offset-3"><a
                style="color: black; font-weight: bold;">Add</a></button>
    </form>

{% endblock %}

tracker/templates/tracker/base.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <title>{% block title %}Trackr{% endblock %}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tracker/material/button/button/dist/mdc.button.css' %}">
    <link rel="stylesheet" href="{% static 'tracker/material/button/ripple/dist/mdc.ripple.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
        button[type=submit] {
            border-radius: 0;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
            border-width: 3px;
            border-color: black;
            background: white;
        }

        table td {
            overflow: hidden;
        }
    </style>
</head>

<!-- <body background="{% static '/tracker/images/background-image2.png' %}" style="font-family: 'Raleway', sans-serif;"> -->
<body style="font-family: 'Raleway', sans-serif; background-color: whitesmoke;" onload="clickBtn()">
<!-- Navigation -->
<header>
    <div class="container" style="padding-top: 10px;">
        <nav class="navbar navbar-default" role="navigation"
             style="position: relative; border-radius: 0; border-width: 3px; border-color: black;">
            <div class="navbar-header" style="float: left; padding: 15px; text-align: center; width: 100%">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'tracker:index' %}"
                   style="font-family: 'Satisfy', cursive; font-size: 30px; position: absolute; left: 50%; margin-left: -50px !important; display: block; color: black;">Tracker</a>
            </div>
            <div class="navbar-collapse collapse" id="topNavBar">

                <ul class="nav navbar-nav navbar-left" style="font-size: 20px; font-weight: bold;">
                    <li class="{% block home_active %}inactive{% endblock %}"><a href="{% url 'tracker:home' %}"
                                                                                 style="color: black;">HOME</a></li>
                    {% if user.is_authenticated %}
                        <li class="{% block tracker_active %}inactive{% endblock %}"><a
                                href="{% url 'tracker:tracker_app' %}" style="color: black;">TRACKER</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right"
                    style="font-size: 20px; font-weight: bold; padding-right: 15px;">
                    {% if user.is_authenticated %}
                        <li class="{% block account_active %}inactive{% endblock %}"><a
                                href="{% url 'tracker:index' %}"
                                style="color: black;">{{ user.username }}</a>
                        </li>
                        <li class="{% block logout_active %}inactive{% endblock %}"><a href="{% url 'tracker:logout' %}"
                                                                                       style="color: black;">LOGOUT</a>
                        </li>
                    {% else %}
                        <li class="{% block register_active %}inactive{% endblock %}"><a
                                href="{% url 'tracker:register' %}"
                                style="color: black;">REGISTER</a>
                        </li>
                        <li class="{% block login_active %}inactive{% endblock %}"><a href="{% url 'tracker:login' %}"
                                                                                      style="color: black;">LOGIN</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </nav>
    </div>
</header>

<main>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
</main>


<div class="container">
    <div class="footer">
        <div style="padding: 12px; background: #f5f5f5">
            <br><br><br><br><br><br><br>
            <div class="row">
                <div class="col-xs-12" align="center">
                    <span align="center" id="footer-copyright">Copyright (c) 2017 by Marc Friedrich</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{% static 'tracker/js/custom.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'tracker/material/button/ripple/dist/mdc.ripple.js' %}"></script>

<script>
    var a = document.querySelectorAll('.mdc-button');
    for (var i = 0; i < a.length; ++i) {
        mdc.ripple.MDCRipple.attachTo(a[i]);
    }
</script>
</body>

</html>

tracker/templates/tracker/edit_track.html
{% extends "tracker/base.html" %}

{% block title %} Edit Track {% endblock %}

{% block tracker_active %} active {% endblock %}

{% block body %}

    <form class="form-horizontal col-sm-offset-3" action="" method="post" role="form" enctype="multipart/form-data">
        <!-- Security -->
        {% csrf_token %}
        {% include "tracker/form_template.html" %}
        <button type="submit" class="custombtn btn col-sm-offset-3"><a style="color: black; font-weight: bold;">Apply</a></button>
    </form>

{% endblock %}

tracker/templates/tracker/form_template.html
{% for field in form %}
    <div class="row">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger-small">{{ field.errors }}</span>
            </div>
            <label class="col-sm-3 control-label" style="text-transform: uppercase;">{{ field.label_tag }}</label>
            <div class="col-sm-9" style="">
                {{ field }}
            </div>
        </div>
    </div>
{% endfor %}

tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}

{% block title %} Trackr {% endblock %}

{% block home_active %} active {% endblock %}

{% block body %}
    <h1>Welcome</h1>
    <p>Welcome to Tracker.</p>
    <br>
{% endblock %}

tracker/templates/tracker/login_form.html
{% extends "tracker/base.html" %}

{% block title %} Login {% endblock %}

{% block login_active %} active {% endblock %}

{% block body %}

    {% if login_error %}
        <p class="col-sm-offset-4">{{ login_error }}</p>
    {% endif %}
    <form class="form-horizontal col-sm-offset-3" action="" method="post" role="form">
        <!-- Security -->
        {% csrf_token %}
        {% include "tracker/form_template.html" %}
        <button type="submit" class="custombtn btn col-sm-offset-3"><a
                style="color: black; font-weight: bold;">Login</a></button>
    </form>

{% endblock %}

tracker/templates/tracker/register_form.html
{% extends "tracker/base.html" %}

{% block title %} Register {% endblock %}

{% block register_active %} active {% endblock %}

{% block body %}

    <form class="form-horizontal col-sm-offset-3" action="" method="post" role="form" enctype="multipart/form-data">
        <!-- Security -->
        {% csrf_token %}
        {% include "tracker/form_template.html" %}
        <button type="submit" class="custombtn btn col-sm-offset-3"><a style="color: black; font-weight: bold;">Register</a></button>
    </form>

{% endblock %}

tracker/templates/tracker/registration_success.html
{% extends "tracker/base.html" %}

{% block title %} Login {% endblock %}

{% block login_active %} active {% endblock %}

{% block body %}

    <p><h4 style="color: gray; opacity: 1.0;">Thanks for registering <b>{{ username }}</b>! You can now login.</h4></p>

{% endblock %}

tracker/templates/tracker/track_confirm_delete.html
{% extends "tracker/base.html" %}

{% block title %} Delete Track {% endblock %}

{% block tracker_active %} active {% endblock %}

{% block body %}

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the item?</p>
        <input class="btn btn-danger" type="submit" value="Confirm"/>
        <button class="btn btn-default" onclick="window.history.back();" type="button">Cancel
        </button>
    </form>

{% endblock %}

tracker/templates/tracker/track_form.html
{% extends "tracker/base.html" %}

{% block title %} Register {% endblock %}

{% block register_active %} active {% endblock %}

{% block body %}

    <form class="form-horizontal col-sm-offset-3" action="" method="post" role="form" enctype="multipart/form-data">
        <!-- Security -->
        {% csrf_token %}
        {% include "tracker/form_template.html" %}
        <button type="submit" class="custombtn btn col-sm-offset-3"><a style="color: black; font-weight: bold;">Register</a></button>
    </form>

{% endblock %}

tracker/templates/tracker/tracker_view.html
{% extends "tracker/base.html" %}

{% load staticfiles %}

{% block title %} Track your progress {% endblock %}

{% block tracker_active %} active {% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-10">

        </div>
        <div class="col-md-2">
            {#            <button class="mdc-button"#}
            {#                    style="font-family: 'Raleway', sans-serif; font-weight: bold;"><span#}
            {#                    class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Add#}
            {#            </button>#}
            <a href="{% url 'tracker:add_track' %}" style="color: gray; opacity: 1.0; font-size: 15px;"><span
                    class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Add</a>
        </div>
    </div>
    <br>

    {% if all_tracks %}
        <table class="col-sm-offset-1 col-sm-10" style="color: gray; opacity: 1.0; font-size: 30px;">
            <tr>
                <th>#</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;Title</th>
                <th>Season</th>
                <th>Episode</th>
                <th></th>
                <th></th>
            </tr>
            {% for track in all_tracks %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;{{ track.title|truncatechars:20 }}</td>
                    <td><span
                            style="font-size: 24px;">Season:&nbsp;<a href="{% url 'tracker:dec_season' track.id %}"
                                                                     style="color: gray; opacity: 1.0; font-size: 30px;"><span
                            class="glyphicon glyphicon-minus"
                            style="font-size: 14px;"></span></a>&nbsp;<span
                            style="">{{ track.season }}</span>&nbsp;<a href="{% url 'tracker:inc_season' track.id %}"
                                                                       style="color: gray; opacity: 1.0; font-size: 30px;"><span
                            class="glyphicon glyphicon-plus"
                            style="font-size: 14px;"></span></a></span>
                    </td>
                    <td>
                        Episode: &nbsp;<a
                            href="{% url 'tracker:dec_episode' track.id %}"
                            style="color: gray; opacity: 1.0; font-size: 30px;"><span
                            class="glyphicon glyphicon-minus"
                            style="font-size: 14px;"></span></a>&nbsp;<span
                            style="">{{ track.episode }}</span>&nbsp;<a href="{% url 'tracker:inc_episode' track.id %}"
                                                                        style="color: gray; opacity: 1.0; font-size: 30px;"><span
                            class="glyphicon glyphicon-plus"
                            style="font-size: 14px;"></span></a>
                    </td>
                    <td>
                        <a href="{% url 'tracker:edit_track' track.id %}"
                           style="color: gray; opacity: 1.0; font-size: 15px;"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Edit</a>&nbsp;&nbsp;&nbsp;
                    </td>
                    <td>
                        <a href="{% url 'tracker:delete_track' track.id %}"
                           style="color: gray; opacity: 1.0; font-size: 15px;"><span
                                class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp;Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p><h4 style="color: gray; opacity: 1.0;">Your list is empty! :(</h4></p>

        <p><h4 style="color: gray; opacity: 1.0;">Why don't you start by adding a new track?</h4></p>
    {% endif %}
    <!-- Interaction error message -->
    {% if messages %}
        <script>
            {#            $("#messages-modal").modal("toggle");#}

            function clickBtn() {
                document.getElementById("modalBtn").click();
            }
        </script>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".messages-modal" id="modalBtn"
                style="display: none;">Small
            modal
        </button>

        <div class="modal fade messages-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
             aria-hidden="true" id="messages-modal">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <ul class="messages" style="list-style-type: none;">
                        {% for message in messages %}
                            <li class="{{ message.tags }}"
                                style="padding-left: 0px; padding-right: 10%; padding-top: 10px; padding-bottom: 10px;"
                                align="center">{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}